### ISSUE TITLE
ID19 update

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#14]
As also 'warned' by Christoph, I see new technology combs. in the ID19 (chp_gas_lightoil 2016 and 2030 and generator_combustionengine_naturalgas for 2016 and 2030) which for some regions have installed capacities and expansion limits however there is no corresponding data for investment costs, lifetime, variale costs, fixed costs and efficiencies. Am I overlooking something?

**Comment by sonercandas** [comment]
Dear Stefanie, this I had also noticed last week.

One solution that we could take (and the one that I took for my first round of runs) is to take the same economic and technical parameters as the other processes with the type chp_gas and generator_combustionengine. The processes are already there, but using other fuels than the ones you described above.

Of course, in case we have the data for these specific fuel&plant types, we should use them.

**Comment by chrwm** [comment]
Hi both, regarding the process with the type _chp_gas_ I agree with Soner. The source mentions light oil as an alternative fuel for the technology. 
Regarding the process with the type _generator_combustionengine_ the source offers the technology with the fuel natural gas and indicates ~25% lower variable costs and a ~6% higher efficiency (48% compared to 45%) with otherwise the same parameter values. The differences are not too big, but I can update it in the next ID.

**Comment by StefanieBuchholz** [comment]
Thank you both very much for the clarification! 
Personally, it is easier for me if the data is there for each technology even if it is just a copy of the data. However, I can manually correct this case in my code, so if it is too much work, I will manage :)

**Comment by chrwm** [comment]
No worries, I will update it in the next ID, and add both techs as described that you don't have to manually copy&paste.

**Comment by chrwm** [comment]
> No worries, I will update it in the next ID, and add both techs as described that you don't have to manually copy&paste.

The update is implemented in ID21.
