### ISSUE TITLE
[model] Bugs in hourly data ID23

### ISSUE THREAD

**Issue by LKoeckritz** [open-modex/models#17]
When I download the hourly data of ID23, there are some issues with the electricity demand data.

For example, the electricity demand in TH for 2016 is 
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.023, 0.057, 0.085, 0.094, 0.085, 0.053, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.003, 0.047, 0.104, 0.16, 0.186, 0.158, 0.1, 0.022, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.015, 0.115, 0.232, 0.329, 0.355, 0.31, 0.195, 0.046, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005, 0.048, 0.093, 0.125, 0.134, 0.108, 0.055,  ...

When comparing with previous hourly data, we notice that there is a shift between regions. What used to be the data for ['BE'] is now the data for ['BB'].

Is this an issue with our data download or with the upload of the data - i.e. do others see the same when checking the hourly electricity demand data?

[Since this is my first issue, please edit/tag this issue to the requirements :) ]

**Comment by henhuy** [comment]
if others don't see this - it could be a mapping error...
Did you check raw data in OEP?

**Comment by LKoeckritz** [comment]
Yes, I checked the raw data. This is the data that I get when downloading.
[Modex_Timeseries_ID23.xlsx](https://github.com/open-modex/models/files/6235783/Modex_Timeseries_ID23.xlsx)

Currently, we are solving using the demand from ID19 since we thought that there were no edits.

**Comment by khainsch** [comment]
The issue remains, also in ID 25. I attach two screenshots (one from ID19 where it still was correct, one for ID25 where it is not anymore). Could the other developers please check if they encounter the same issue?

1.1: ID19: Demand in Thüringen (everything fine)
![image](https://user-images.githubusercontent.com/53045125/114557642-2a97f400-9c6a-11eb-9d9a-8832db80f237.png)

1.2: ID25: Demand in Thüringen (as you can see, the 2016 values are a solar timeseries)
![image](https://user-images.githubusercontent.com/53045125/114556400-f6700380-9c68-11eb-86b5-b96a5f082e61.png)

2.1: ID19: SolarPV timeseries in Thüringen (everything fine)
![image](https://user-images.githubusercontent.com/53045125/114557705-397ea680-9c6a-11eb-9568-477b701b971b.png)

2.2: ID25: Solar PV Timeseties in Thüringen (can produce during the night, not good)
![image](https://user-images.githubusercontent.com/53045125/114556863-6a121080-9c69-11eb-97a3-cc049da3dd3d.png)


Generally, it seems that at some point, all timeseries are shifted to the "left". I only show the examples for Thüringen, as it is the last region and the effects are the most drastic here, as data of completely different time series can be found. However, also demand series for BW (for example) are now demand series for BE, which obviously is a problem. Not sure if that is an issue which only occurs when downloading the csv file, so if others could check, that'd be really good.

**Comment by StefanieBuchholz** [comment]
Dear all, 

Since I just returned from vacation i am not sure what the status of this issue is. However, today i wanted to update Balmorel for the new ID25 and I think I encounter similar problems as the ones described here (however it might be something else). 

Anyway, I am using the following mapping/command to get the timeseries csv file: 
https://modex.rl-institut.de/scenario/id/25?source=modex&mapping=timeseries&output=csv

When I do so, the naming in 2016 is wrong since, e.g. the very first entry is 'TH.hydro.turbine.run.of.river.installed.capacity' which does not have anything to do with the timeseries data. In both 2030 and 2050 for ID25 the first entry is "TH.unknown.unknown.demand".  I therefore started comparing the ID25 to the ID19 data and what I found was that the naming in 2016 is wrong while the naming in 2030 and 2050 are shiftet so that TH comes before all other regions -  where according to the data it should be the very last region. This seems to happen with the demand and with the hydro capacity factor where the TH hydro CF seems to be put before all CF timeseries. I therefore fixed the problem by rearranging the names of the columns. Since the naming of 2016 was wrong I used the names of 2030. The new order of the column names should be as follows (which would fit with the data in the corresponding columns when comparing to the data in ID19):

c(names(oed_timeseries_full_2030)[2:16],names(oed_timeseries_full_2030)[1],names(oed_timeseries_full_2030)[18:81],names(oed_timeseries_full_2030)[17],names(oed_timeseries_full_2030)[82])

Basically I start with the names of column 2:16 and then I add the name of column 1, then I follow with name 18:81 and I then put in name 17 and at last name 82. 

name (2:16): demand of all regions except TH
name (17): demand of TH
name (18:81): all cf profiles for all regions except hydro cf for TH
name (17): hydro cf profile for TH
name (82): timeindex name

I change the naming for each year by this: 

names(oed_timeseries_full_2016) <- c(names(oed_timeseries_full_2030)[2:16],names(oed_timeseries_full_2030)[1],names(oed_timeseries_full_2030)[18:81],names(oed_timeseries_full_2030)[17],names(oed_timeseries_full_2030)[82])

names(oed_timeseries_full_2050) <- c(names(oed_timeseries_full_2030)[2:16],names(oed_timeseries_full_2030)[1],names(oed_timeseries_full_2030)[18:81],names(oed_timeseries_full_2030)[17],names(oed_timeseries_full_2030)[82])

names(oed_timeseries_full_2030) <- c(names(oed_timeseries_full_2030)[2:16],names(oed_timeseries_full_2030)[1],names(oed_timeseries_full_2030)[18:81],names(oed_timeseries_full_2030)[17],names(oed_timeseries_full_2030)[82])

This may seem very confusing and again, i am not sure if it is the name error that you refer to or if I just do something wrong. I do however expect the timeseries mapping to have changed somehow, but I am not sure if that is true? 

best regards, 

Stefanie

**Comment by khainsch** [comment]
Seems like the very same error, we get the data using the same methodology.

We chose a more "simple" way of dealing with that problem, as we just continue using the data from ID19. However, if you also encountered this issue, it might be something more serious.

**Comment by henhuy** [comment]
I found out that this is an error in normalization of upload data. Fixing it... (will be a new scenario ID)
Download mapping is correct as far as I can see.

**Comment by henhuy** [comment]
Should be fixed in scenario with **ID27** - could you check?

**Comment by StefanieBuchholz** [comment]
Hi @henhuy :) 

Thanks for looking into it!
I just checked the ID27 and it is almost working. Basically 2016 and 2030 are both correct and 2050 are correct except for the very last column name (before timeindex) which is missing. This means that 2050 has 81 column names while 2016 and 2030 have 82 column names. The name that is missing should be on spot 81 and it should be 'TH.hydro.turbine.run.of.river.capacity.factor'. This is the only error I see in ID27 :)

**Comment by henhuy** [comment]
ah okay! :( Will look into this as well...

**Comment by henhuy** [comment]
Should be fixed with Base Scenario ID30
Thanks for checking data!
