### ISSUE TITLE
Proposal to add import/export to region demand timeseries

### ISSUE THREAD

**Issue by jonasVano** [open-modex/models#22]
Hi all, 

I have a proposal and I hope I am not too late with it. Why haven't we simply added the timeseries for import and export to neighbouring countries to the demand timeseries of the region connected to the country? wouldn't that have been easier? I would be happy to have such an option as it is a bit difficult for me to integrate that into the model. I think it is not that much effort to still make that option possibel, right? 

For Base 2016: I think we have to add export here because otherwise a large share of demand is missing as the exports were quite high in recent years. Also, for the policy paper we need to be as close as possible to the actuall generation in 2016 because otherwise the paper is a joke or we really have to explain ourselves. :)

Let me know what you think!

Best
Jonas

**Comment by StefanieBuchholz** [comment]
Hi

I guess my questions to the new 'trade' data fits here - First, thanks for clarifying the interpretation of ‘trade’ yesterday. 
However, just now I realize that I might still not be completely sure what the idea is, and how the data fits the idea.
From our discussion yesterday I understood that

**We assume that the trade.volume timeseries is fixed hourly trade and that this hourly trade happens at the hourly price in the timeseries trade.price**

Then questions: 
1) Why do we then have fixed trade for 2016, 2030 and 2050 but only prices for 2030 and 2050? 
2) Why do we have an ‘installed capacity’ for ‘trade’? I mean, if we can just add or subtract the trade.volume from the demand, would the installed capacity then have any meaning?  (For the model only having fixed trade it would be redundant to have installed capacity as this then only relates to a question of feasibility in input data)

**Comment by jonasVano** [comment]
1. Good question, we also should have prices for 2016 actually ...
2. I think some models can model the capacities with fixed timeseries. But I just don't use those capacities. So depends on how you want to model it I would say :)

**Comment by StefanieBuchholz** [comment]
Thanks for a fast answer! 
1) With prices added for 2016, it makes sense to me. Also, @chrwm could it be that the trade.volume has a mistake since with the new ID32 data I all of a sudden get a 'NS-transmission-trade-trade volume' profile and we have not earlier considered a NS region? 
2) I will ignore the capacities for now as well then. To this I can add, that yesterday in the mathematical comparison group we had a discussion whether we should make an analysis where the frameworks that can make additional trade for the price within the capacities are allowed to do so (to show differences in the framework). However, this morning I found out that the trade-addon in Balmorel is based on an estimated stepwise price function and not an hourly timeseries. I could implement it with the timeseries instead but I am also very(!) fine with just having the fixed trades and paying for these (and ignoring capacities) - but others opinion on this is highly welcome

**Comment by StefanieBuchholz** [comment]
* NS also(!) part of the trade.price timeseries

**Comment by jonasVano** [comment]
Good question, what is NS? :)

**Comment by jonasVano** [comment]
I have ignored that as well...

**Comment by sonercandas** [comment]
I would vote here, that each framework models the imports/exports in the way they can (i.e. exogenously by fixed volumes, or endogenously by constant/hourly prices/capacities). I think it would be interesting when we then showcase the differences in results. What do the others think?

**Comment by chrwm** [comment]
Hi all,
1. For 2016 federal state-specific prices couldn't be found and in mid-March it was decided to leave them out.
Yes NS was a typo and should have been NI -> This is already corrected and uploaded in ID33.
2. Exactly as Jonas said the capacities could be necessary for modelling trade other than adding or subtracting it from the demand. 
I agree with Soner the difference in results could be very interesting using different modelling approaches. 
However, I would argue at least for one model run in the base scenario with the same approach across all frameworks (I guess adding/substracting to demand can be implemented in all) for comparability reasons.

**Comment by khainsch** [comment]
Hi all,

one thing now that we found in ID33 is that in SH, for some of the hours the imports **exceed** the demand. If we go with the proposed solution of just adding net-export to the demand, this results in a negative demand for these hours which our Framework is not really suited to handle, I expect the same situation might occur for others.

The "clean" way of implementing this in our case would be to define an import and an export technology, which then have "fixed" production for the respective hours. However, especially the export technology would need some finetuning: do we assign costs (negative?) to it and allow overproduction to export electricity? Is it "just" a dummy and export is not allowed apart from the given values? 

How would the case be for the other developers? Do you have an issue with negative demands?

**Comment by StefanieBuchholz** [comment]
Hi all, 

I saw that a new data ID was uploaded today (ID 34) and in the comments it says '* Updated trade volume data in oed_timeseries in 2016'. Maybe this has the purpose of 'solving' the negative demands? I have not checked yet, but in Balmorel I implemented the import and export seperately from the demand and therefore negative demand does not seem to be a problem for me.

**Comment by khainsch** [comment]
Okay, will check, thanks Stefanie.
One question with respect to the export technology: do you allow the model to export electricity (at which price? Same as the import price?) Or is it just a placeholder and all trade volumes are fixed and not subject to the optimization?

**Comment by StefanieBuchholz** [comment]
I have decided (for now) just to work with fixed import/export corresponding to the traded volumes. So the model trades what the trade timeseries suggest and the trade happens at the prices in the price timeseries.  Therefore, the whole thing is currently just a 'constant' to the model and therefore not affecting the optimization. I understand that, the idea of having it is that it changes the demand pattern and enables us to compare the results to historical values. 

Balmorel is also able to have additional trade which I have been talking to Soner and Christoph about. The idea would then be to let the model optimize the trading when using the price timeseries as driver. However, Balmorel is not using an hourly price timeseries for this, but a stepwise approximation - and therefore I would have to implement it seperately with the prices we have. I therefore prefer not to do so :)

**Comment by chrwm** [comment]
@khainsch 
> If we go with the proposed solution of just adding net-export to the demand, this results in a negative demand for these hours which our Framework is not really suited to handle,

The trade volumes are aggregated so that "negative values are net import (imports are higher than exports)". This is stated also in the "comment" column. This would mean that if you would add "net-export" it should be a positive trade volume added to a federal state demand. 
I recognise the fact that the demand+trade volume in a federal state may become negative. I just wanted to say that to avoid confusion.

@StefanieBuchholz 
> I saw that a new data ID was uploaded today (ID 34) and in the comments it says '* Updated trade volume data in oed_timeseries in 2016'. Maybe this has the purpose of 'solving' the negative demands?

The updated trade volume time series ensures that the total trade volume across all federal states in 2016 corresponds to a net export of 49TWh according to historical data. It does not address the problem of possible negative demand in individual federal states per time step.

**Comment by jonasVano** [comment]
Okay, so negative damand values are a problem. I wouldn't have thought that something like this could even happen. I think we have to fix this somehow :(
So first of all, does someone have an overview how many negative values do we get? Is this just for very few time steps or does this occur regularly?

**Comment by khainsch** [comment]
@chrwm 
> The trade volumes are aggregated so that "negative values are net import (imports are higher than exports)". This is stated also in the "comment" column. This would mean that if you would add "net-export" it should be a positive trade volume added to a federal state demand.

Sorry for the misunderstanding, what I meant by "net-export" is that positive values are exports, negative imports which is why I called it that way. :)

@jonasVano
> So first of all, does someone have an overview how many negative values do we get? Is this just for very few time steps or does this occur regularly?

For 2016, there are 120 values for SH which are negative, for 2030 we are talking about 1414 hours and for 2050 200. So I think the option from Stefanie would be the cleanest way to include two technologies (one for export and one for import) with the respective time series. Would love to hear how other frameworks would ideally implement this.

**Comment by jonasVano** [comment]
So we found the solution to the Problem: 

**Exports**: We add them as positive values to the demand to increase the demand 
**Imports**: We model an inflexible power plant with a pre-defined timeseries as output that corresponds to the imported energy

The changes will be added in the final update of the input data in the coming days.

**Comment by chrwm** [comment]
I just need some details on how you decided to model it, for implementing it in the input data. The "trade volume" timeseries is currently given as the sum of imports and exports.
Do you want to split the data as in the table below?

<table>
<thead>
<tr>
<th>timestep</th>
<th>trade volume</th>
<th>import</th>
<th>export</th>
</tr>
</thead>
<tbody>
<tr>
<td> 1 </td>
<td>280.65  </td>
<td>0</td>
<td>280.65</td>
</tr>
<tr>
<td>2</td>
<td>55.55 </td>
<td>0</td>
<td>55.55 </td>
</tr>
<tr>
<td>3</td>
<td>-20.5 </td>
<td>-20.5 </td>
<td>0 </td>
</tr>

</tbody>
</table>

For 2016, I can disaggregate the data specifically to import and export, as the data is available.

<table>
<thead>
<tr>
<th>timestep</th>
<th>trade volume</th>
<th>import</th>
<th>export</th>
</tr>
</thead>
<tbody>
<tr>
<td> 1 </td>
<td>280.65  </td>
<td>-10</td>
<td>290.65</td>
</tr>
<tr>
<td>2</td>
<td>55.55 </td>
<td>-244.45</td>
<td>300 </td>
</tr>
<tr>
<td>3</td>
<td>-20.5 </td>
<td>-500 </td>
<td>479.5 </td>
</tr>

</tbody>
</table>

For 2030 and 2050, however, I cannot, as just the sum of imports and exports is available to me. If you intended the implementation in the 2nd table, then @sonercandas can you provide the disaggregated imports and exports from the precalculations?

What did you decide with regard to the trade prices in 2030 & 2050?

**Comment by sonercandas** [comment]
Hi Christoph, in the table I had provided, we indeed see the net export or import happening in a given time step. So if the value is positive, it would be an export timestep. and if negative it would be an import timestep. 

That way, at least how I see it, we should 
-take the timesteps with positive values (export) as "extra demand" and 
-take the timesteps with negative values (import) as the dummy power plant production?

**Comment by chrwm** [comment]
Hi Soner, I implemented it as you said.
I split the 'trade volume' as shown in the first table above.
- The positive values are in the timeseries "trade export" and should be added to the demand
- The negative values are normalised between [0,1] and correspond to a dummy power plant with 'technology_type' = 'trade import'. It has specific regional 'installed capacity', due to the normalisation. 
Hence the technology should behave like a renewable technology with capacity factor.
