### ISSUE TITLE
Modelling the RE share

### ISSUE THREAD

**Issue by srhbrnds** [open-modex/models#6]
## Issue description
We identified that the RE share in some FWs can not be directly implemented as an existing parameter/constraint. Please describe how you modeled the RE-Share!

**Comment by khainsch** [comment]
GENeSYS-MOD:
Technologies can be tagged as renewable. Then, a constraint makes sure that the production from renewables (in a sector or overall) has to be at least the defined RE Share out of total production (in the sector or overall).

**Comment by sonercandas** [comment]
urbs:
-We can define a new commodity called "Elec_RE".
-We add this new commodity as another input commodity to all RE technologies, with the input ratio equal to the Elec output ratio.
-In urbs, we can define a maximum created amount of commodities. We now add a single new constraint, with which one can also set a "minimum creation" of commodities, which we will apply to Elec_RE.
-For each region, we set these minimum amounts equal to the "electricity demand in that region * x%". 
If I am not missing something, this should work, but I will let you know of the outcome here.

**Comment by StefanieBuchholz** [comment]
Balmorel: (Similar to GENeSYS-MOD, I believe)
It is possible to assign each technology to a technology group, by using a tag in the input file. I here create the tag 'RENEW' and assign all Wind, Solar, Hydro, Geothermal, Biomass, and Biogas technologies to this tag. 

I then introduce a new constraint (QRSHARETECHGROUPC(Y,C,TECH_GROUP)  "Minimum generation by year, country and technology group (MW)") that for a year Y, and a country C (DE in our case) and a technology group puts a lower bound on the total generation from this technology group. The lower bound is set to be the renewable share (input data) multiplied by the total generation of year Y from all technologies (independent on technology group).

**Comment by jonasVano** [comment]
I really don't know how to do this, I cannot set anything like that. I think I have to run multiple times and just see when the share is met

**Comment by chrwm** [comment]
Shall we define a common definition of the RE share, as Simon suggested in today's meeting, to prevent different results stemming from different contextual interpretations of the RE share? So that when differences occur we are confident that they stem from different modeling approaches based on a common understanding of the RE share?

**Comment by srhbrnds** [comment]
Summary from Telko: not every model is able to implement RE share similarily, so we do a mixture, some FWs use RE share other use CO2 budget (sector budget)

From 2016 we can identify model differences. From 2030 and 2050 we find interpretations of the different approaches.

**Comment by jonasVano** [comment]
So to sum up the points that I just mentioned:

In my opinion we have two options: either we leave the renewable share out or we do a mixure because some models (like GENESYS-2) cannot model a renewable share. They however can model a CO2 budget that should theoretically lead to similar results. I would prefer that every framework does it the way it can do it best. We have already the 2016 scenario, where we have no special constraints and everything should be modelled the same. So we can take that scenario for a more detailed comparison and use the 2030/2050 scenario to show what different interpretations of renewable targets can look like when using enery system models. In the end it can just be interpreted the way that we want anyway because there are so many degrees of freedom in the analysis that we are doing.

If you disagree let us know here :)

**Comment by StefanieBuchholz** [comment]
Since noone disagreed to your point Jonas, I believe we can conclude that your suggestion is what we do and then close this?
