### ISSUE TITLE
Waste commodity limit is global, how to allocate to regions?

### ISSUE THREAD

**Issue by sonercandas** [open-modex/models#7]
As i understand from the input file, the domestic limit for waste commodity is given for the whole Germany. However, in Urbs at least, these commodity limits are to be set on each model region instaed. There, i see two options:

a) we need to find a way to allocate these limits to each region (by installed capacities in each?)
b) I need to hard-code a dummy "transmission system for waste" in urbs, where the waste commodities are generated in one of the regions and then freely can be transported to any other region. 

The choice b) would increase the model complexity a bit, so I wanted to ask, if some of the other frameworks have the similar problem? Then we could think of an allocation method.

**Comment by chrwm** [comment]
We can collect the other FW maintainer assessment on the topic. 
From the discussion 18.02.21 the following was noted:
Balmorel: Can handle the current input data, as limits for either techs or regions are set. The waste limit is set for the region.

**Comment by jonasVano** [comment]
GENESYS can only define global levels...

**Comment by sonercandas** [comment]
**with urbs we will pick the solution of "waste transmission". (option b)**

**Comment by StefanieBuchholz** [comment]
Data point to this issue: 

I actually did not realize that the waste was a limit for 'DE' since it was stated with "['BB', 'BE', 'BW',   'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']". For comparison, we have the co2 emission limit stated for 'DE' while parameters such as capital costs, input/output ratios etc.  are stated for "['BB', 'BE', 'BW',   'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']", with the understanding that they apply within each region. Consequently, I understood the domestic waste limit as a limit that applies within each region. For consistency reasons I would therefore say that the domestic limit for waste should have the region 'DE' instead. In my data code I can make this change manually, but I imagine that it could create some confusion when mappings are used?

**Comment by sonercandas** [comment]
> Data point to this issue:
> 
> I actually did not realize that the waste was a limit for 'DE' since it was stated with "['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']". For comparison, we have the co2 emission limit stated for 'DE' while parameters such as capital costs, input/output ratios etc. are stated for "['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']", with the understanding that they apply within each region. Consequently, I understood the domestic waste limit as a limit that applies within each region. For consistency reasons I would therefore say that the domestic limit for waste should have the region 'DE' instead. In my data code I can make this change manually, but I imagine that it could create some confusion when mappings are used?

Good point, so did i actually interpret it wrong? @chrwm

**Comment by chrwm** [comment]
It is like Stefanie said. The data itself describes the available amount of waste of whole Germany. 
Hence the annotation in its current state is confusing and should be changed to ['DE']. 
I will do that in ID19.

**Comment by chrwm** [comment]
> Hence the annotation in its current state is confusing and should be changed to ['DE'].
> I will do that in ID19.

The change is implemented in ID19.
