### ISSUE TITLE
How to handle gap year in each FW?

### ISSUE THREAD

**Issue by chrwm** [open-modex/models#9]
We found that Balmorel and GENeSYS-MOD might have problems to implement the 8784h in 2016.
Current implementations:

- Balmorel: cut off last 49h of the timeseries
- GENEeSYS-MOD: may encounter problems and need to cut off a day
- urbs: no problem

If days are cut off make sure to communicate your solution for harmonisation reasons.

**Comment by jonasVano** [comment]
No Problem for GENESYS-2

**Comment by khainsch** [comment]
Since this might become relevant in the scenario variations, we can discuss in how far we want to streamline this at that point or if we go with "That is framework functionality and the frameworks can decide how to handle it".

@StefanieBuchholz In your implementation of the base scenario, did you (i) already cut off some of the hours or (ii) calculate single years where this does not become an issue?

**Comment by StefanieBuchholz** [comment]
Currently I have (i) cut off some of the hours also in the single year runs, in order to make the data code directly useable for the pathway run. 

As we discussed yesterday, I believe I could handle all hours in the single year calculations but as you, I would have to cut off hours when we move to the pathway. If someone has a strong opinion that I should do so, I will, but generally, my opinion is that, since some frameworks at some point have to cut off hours (even though it is in one of the scenario variations) I think it would be better to cut off these hours in the data so that all frameworks use the same timeseries at all times (both in single year runs and pathway runs). In that way, we know that potential differences do not come from the cutt-off hours and In the documentation we can mention that this is a limitation for some frameworks. I do not think that we lose much value in cutting off some days.

**Comment by jonasVano** [comment]
Lets cut off the hours. I think that would be okay. For 2016 it is not trivial, because I think we need to be careful to get similar results like the historic data shows but one day is probably not gonna make that much of a difference. Or should we probably just add the demand of that one day linearly to all days?

**Comment by StefanieBuchholz** [comment]
I do believe that we still need a conclusion on this - exactly which hours should be cut off? 
I would suggest to take it up in the next meeting so that we can adjust the model runs now instead of later. 
Can we think about what our opinion is before the nest meeting?

**Comment by jonasVano** [comment]
I have put it on my list for the next meeting :)

**Comment by srhbrnds** [comment]
In my opinion, I wouldn't cut off the hours in the base scenario. Because here, we can reach the goal of having a comparable scenario without artificially cutting of a day, which i think is not trivial (At least we would need to make sure that the day you cut off  is no day with peak demands or extreme weather conditions). Of course comparability is our main objective but I think we should also not reduce the FW comparison too much to the shortcomings, especially when it comes to the scenario variations. For the base scenario that was the idea- having a sort of lowest common denominator scenario. This, we can reach without cutting off certain hours. For the variations: we also wanted to showcase certain functionalities and classify strengths and weaknesses. 
If we argue that we cold cut off one day because it won't change the results too much, then I would suggest we use the same argument to not cutting one day off and explain the small difference in the results with exactly the way how the FWs are capable of handling gap years.
